### ISSUE TITLE
Loading Litematic Schematic with negative position value causes InvalidValue Error instead successful load

### ISSUE THREAD

**Issue by HafiTheCat** [SlopeCraft/mc_schem#1]
# Actual Behavior
Loading a schematic with negative `Position x` value in the following way

```rust
use mc_schem::schem::Schematic;

fn main() {
    let res = Schematic::from_file("Supercharged_contained_shulker_farm.litematic");
    dbg!(res);
}
```

will result in the following error:

```rust
Err(InvalidValue {
        tag_path: "/Regions/Supercharged_contained_shulker_farm/Position/x",
        error: "Expected non-negative value, but found -31",
})
```

# Expected Behavior
Loading a schematic with negative `Position x` value will result in a successful load of the schematic

# Steps to Reproduce the Problem
Load any schematic (or used test file below) that contains a negative `Position x` value.

# Specifications
## Rust specifications
Rustc version: rustc 1.76.0 (07dca489a 2024-02-04)
Toolchain: stable-x86_64-unknown-linux-gnu (default)

## Schematic specifications
Type: LITEMATIC
MinecraftDataVersion: 3465
Subversion: 1
Version: 6
Regions: 1

[testSchematic.zip](https://github.com/SlopeCraft/mc_schem/files/15090298/testSchematic.zip)

**Comment by ToKiNoBug** [comment]
I have checked your schematic, the size of region is [-37, 45, -51], that's weird! The shape contains negative number, Is that schematic generated by litematica mod?

**Comment by ToKiNoBug** [comment]
> I have checked your schematic, the size of region is [-37, 45, -51], that's weird! The shape contains negative number, Is that schematic generated by litematica mod?

If litematica do generate such litematica file, if that is a FEATURE of litematica, then I will have to add an additional rule to fix this problem.

**Comment by ToKiNoBug** [comment]
If I have understood the format of litematica file correctly, the size shoule consist of non-negative numbers, and position of a region should be also positive because I believe position refers to the relative position of a region in the whole enclosing size.

**Comment by HafiTheCat** [comment]
> The size of region is [-37, 45, -51], that's weird! The shape contains negative number

yes that confuses me as well. However in `minecraft 1.20.4` it does work importing it with the litematica mod.

> Is that schematic generated by litematica mod?

Yea

On another note I also tried a similar crate called "rustmatica" for loading it. However it results in a very similar error, due to the apparent format definition.

Unfortunately I could not find a proper file format definition of the `.litematica` format so I wasn't able to cross-check it.

**Comment by ToKiNoBug** [comment]
OKay, I will fix this problem.

**Comment by ToKiNoBug** [comment]
> Unfortunately I could not find a proper file format definition of the `.litematica` format so I wasn't able to cross-check it.

I didn't find any document about .litematic either, everything I know about it comes from reverse engineering

**Comment by ToKiNoBug** [comment]
I have fixed this problem, you can find the latest version(1.1.2) on crates.io. Note that parsing minecraft worlds is not fully implemented, this function should be considered as experimental. However you can feel free to manipulate on schematics with that crate

**Comment by HafiTheCat** [comment]
> I have fixed this problem, you can find the latest version(1.1.2) on crates.io. Note that parsing minecraft worlds is not fully implemented, this function should be considered as experimental. However you can feel free to manipulate on schematics with that crate

Thank you so much for your time, it works now :>

> On another note I also tried a similar crate called "rustmatica" for loading it. However it results in a very similar error, due to the apparent format definition.

I'll make an issue on `rustmatica` for it as well!
